# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(default='none', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Add',
        ),
    ]
